### ISSUE TITLE
Initial state of the lib

### ISSUE THREAD

**Issue by greglobinski** [gatsby-inc/gatsby-interface#1]
## Gatsby Interface on Cloud

! The issue describes  initial [state of the repo](https://github.com/gatsby-inc/gatsby-interface/tree/cef9aa70fd1ddd8eb6d27b113275460d796d4639).

The repo contains shared `Buttons` components we use currently on Cloud.

However, the code is not 100% the same with the one we actually use on Cloud. It was refactored to properly presents `prop-types` of components  in Storybook.

- `ButtonSkeleton` - a functional **building block** (extracted from the `BaseButton` currently used on Cloud)
- `BaseButton` - a style base for all shared buttons (never used directly in the app)
- `PrimaryButton`, `SecondaryButton`, `CancelButton`, `PrimaryDeleteButton`, `SecondaryDeleteButton`, `SuccessButton` and `TextButton` - shared components used in Cloud

### Styling

We style the `ButtonSkeleton` by passing to it a `styled` `emotion` (v9) component. 

**BaseButton** (pseudo code)
```
export const StyledBaseButton = styled(`button`)`
  ... styles
`;

const BaseButton = props => (
  <ButtonSkeleton StyledComponent={StyledBaseButton} {...props} />
);
```

**ButtonSkeleton** (pseudo code)
```
const ButtonSkeleton = ({
  StyledComponent,
  children,
  ...
}) => {
  return (
    <StyledComponent >
      {children}
    </StyledComponent>
  );
};
```

Shared Buttons to customize styling overwrite styles of `StyledBaseButton`. 

**PrimaryButton** (pseudo code)

```
const StyledPrimaryButton = styled(StyledBaseButton)`
  background: ${colors.gatsby};
  ...
`;

const PrimaryButton = props => (
  <ButtonSkeleton StyledComponent={StyledPrimaryButton} {...props} />
);
```

### Presentational props

There is only one presentational prop on Buttons - `size`. The prop could get four `values`: `S`, `M`, `L` (default) or `XL`. Three CSS properties respond to changes of it.

```
export const StyledBaseButton = styled(SkeletonStyledComponent)`
  ...
  font-size: ${props => sizes[props.size].fontSize}rem;
  min-height: ${props => sizes[props.size].height}rem;
  padding: ${props => sizes[props.size].verticalPadding}rem
    ${props => sizes[props.size].horizontalPadding}rem;
 ...
`;
```

### Summary

That's the current state. Any comments are welcome.

**Comment by rizchelwood** [comment]
This is awesome :100:
