### ISSUE TITLE
Run lint and format scripts for the codebase

### ISSUE THREAD

**Issue by Elanhant** [gatsby-inc/gatsby-interface#185]
#170 changed the way we format and lint files on commit — now only the staged files are touched (previously the scripts would run for all matching files). Because of this, some of the files in our codebase might not be formatted properly.

Once PRs #169, #183, #178 and #177 are merged, running the following commands should fix formatting for all of the files:
```bash
yarn format "{src,.storybook}/**/*.{js,jsx,ts,tsx}" 
yarn lint src .storybook
```

**Comment by fk** [comment]
Done in #236.
