### ISSUE TITLE
Remove horizontal padding from `Navigation`'s main container

### ISSUE THREAD

**Issue by fk** [gatsby-inc/gatsby-interface#246]
I just wondered if the whitespace to the right of gatsbyjs.com's main navigation might be a little bigger than its opposite on the left side of the main nav—turns out it is:

![image](https://user-images.githubusercontent.com/21834/77012786-f373e800-696e-11ea-8ac9-b79f7367a32a.png)

The [Navigation](https://reverent-keller-9597e8.netlify.com/?path=/story/navigation--with-item-links-as-props-and-button-as-child) component's main container comes with a horizontal padding of `1rem`.

![image](https://user-images.githubusercontent.com/21834/77013771-11dae300-6971-11ea-93a5-72693592835b.png)

I want to suggest to remove https://github.com/gatsby-inc/gatsby-interface/blob/3605753eb1e5783937481655a00d3144f7086b74/src/theme/styles/navigation.js#L43 to keep the component container "context-agnostic".

Please LMK what y'all think—maybe also in regards to allowing to pass in those values, or rather solve this "outside" in some way or another.

**Comment by Elanhant** [comment]
While generally I prefer to stick to the approach of leaving padding values to the component and margins to its parent, I agree that in this case it makes sense to remove the padding rule — after all, the navigation bar doesn't seem to have any visible borders that could warrant setting a padding.

So yeah let'd do it 👍

**Comment by fk** [comment]
👍

**Comment by fk** [comment]
@joshwcomeau I briefly chatted about this with @mfrachet, which made me remember that you implemented the `Navigation` component (?!), and @greglobinski recently added #331 — what do y'all think of this nitpicky issue?
