### ISSUE TITLE
SidebarNav: Consider removing the `FULL` variant

### ISSUE THREAD

**Issue by fk** [gatsby-inc/gatsby-interface#326]
https://github.com/gatsby-inc/gatsby-interface/blob/8038a56acf5eda42ebe72c40c048dde080b4695b/src/components/SidebarNav/SidebarNav.tsx#L63

Should we allow setting `maxWidth` instead?
This feels very "magic number", also IMO the variant name is misleading/confusing.

**Comment by Elanhant** [comment]
Totally agree with you here, and it looks like we don't even use this variant in Cloud.

**Comment by fk** [comment]
👍
