### ISSUE TITLE
Peer Dependency Warning

### ISSUE THREAD

**Issue by schwigri** [gatsby-inc/gatsby-interface#339]
I'm working on a site using Gatsby, but I have no intention of using `gatsby-interface`; I notice this package is a dependency of `gatsby-admin` which is a dependency of Gatsby.

However, I keep getting dependency warnings from NPM as I am using react@16.13.1 but this package requires exactly react@16.8.1. (This same warning occurs for `react-dom`).

I'm not sure the Gatsby flow but is it necessary for this package to be required by Gatsby, or for this package to have a specific React version? Thanks :)

**Comment by Elanhant** [comment]
> I'm not sure the Gatsby flow but is it necessary for this package to be required by Gatsby

If I remember correctly, it is indeed necessary for `gatsby-admin`...

> or for this package to have a specific React version

...but `gatsby-interface` shouldn't really pin to an exact version of React/ReactDOM. I will unpin those 🙂

**Comment by dwilt** [comment]
This would be great as we're seeing this warning in our project too!
