### ISSUE TITLE
v0.0.35 errors in .com

### ISSUE THREAD

**Issue by rizchelwood** [gatsby-inc/gatsby-interface#40]
I published `0.0.35` but I'm getting this error in .com

I will keep it at `0.0.34` for now. I haven't been able to dig into this but it looks like it's having a problem with `filestack` with `gatsby` just from a quick glance

It works fine in storybook

Maybe one of you know more on this? cc: @greglobinski @gillkyle 

<img width="884" alt="Screen Shot 2019-08-28 at 3 03 28 PM" src="https://user-images.githubusercontent.com/18426780/63892638-59822900-c9a5-11e9-929b-8bd2e8ed3549.png">

**Comment by gillkyle** [comment]
Hmmmm. I wonder if Filestack is using some browser globals that need to be wrapped in useEffects or something when initialized.

Though I don't think just installing it should cause the whole build to break unless it's used somewhere and so far it isn't. 🤔

**Comment by rizchelwood** [comment]
@gillkyle have you been able to look more into this?

**Comment by gillkyle** [comment]
No, sorry for the wait. I'll try and prioritize it 👍 got more busy starting school.

**Comment by rizchelwood** [comment]
No worries, thanks!
