### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by Elanhant** [gatsby-inc/gatsby-interface#82]
Currently we have to release `gatsby-interface` manually which is prone to error and inconvenient for contributors. We will benefit from setting up an automated release process.

Two flows I think would be valuable to us:
1. Each commit to `master` triggers a normal release. Ideally, we should adopt some convention that would take care of choosing a new version and generating changelogs (like [standard-version](https://github.com/conventional-changelog/standard-version)).
1. Each commit to `dev` branch triggers a `dev` release — this would allow us to test out new features from `gatsby-interface` and start using them in other code without having to link them via yarn or npm (which are fine, but quite often do not work properly)

**Comment by mfrachet** [comment]
This is a super nice idea!

I'm just wondering about our actual versioning system. What's our standard for creating new version?

I'm saying this because if we decide to rely on semantic versions, we don't have the need for an intermediate branch like dev. We could simply merge on master and deploy the new versions + having the demo available 😄

**Comment by joshwcomeau** [comment]
++ this is a great idea! Although yeah I also wonder about versioning, for non-dev releases. I wonder if maybe in the metadata / PR labels / somewhere we can specify whether a merged update is `major` / `minor` / `patch`, so that it bumps the version correctly?

**Comment by Elanhant** [comment]
> ++ this is a great idea! Although yeah I also wonder about versioning, for non-dev releases. I wonder if maybe in the metadata / PR labels / somewhere we can specify whether a merged update is `major` / `minor` / `patch`, so that it bumps the version correctly?

`standard-version` (link in the issue description) should take are of this as long as we follow conventional commits guidelines. It works something like this:
* if there was a commit with message footer `BREAKING CHANGE:` since the last release, there would be a `major` bump
* if there was a commit with message prefixed with `feat:` since the last release, there would be a `minor` bump
* if there were only `fix:` commits then it would be a `patch` bump

See [conventional commits summary](https://www.conventionalcommits.org/en/v1.0.0/#summary) for more details 🙂

**Comment by Elanhant** [comment]
This is done with #124 and #151
