### ISSUE TITLE
Create Text component 

### ISSUE THREAD

**Issue by rizchelwood** [gatsby-inc/gatsby-interface#86]
In .com we have shared `Typography` file with basic elements we use including Text and Lede. Let's create a Text component so we can pull it from `gatsby-interface` instead. This component will take a `SIZE` (maybe just use the `fontSizes` to be used as the sizes for now - XS, S, M, etc), `VARIANT` (bold, etc), and maybe `TONE` (NEUTRAL (grey), BRAND (purple), not sure if we want one for ERROR and SUCCESS). We should allow to customize rendered element via a prop, e.g. as="p" or as="strong" and not couple styles to HTML tags like h1, h2, etc since that might result in issues with A11y. Let's allow for native margins instead of setting it in the code.

Let me know if you have any questions or need clarification.

**Comment by greglobinski** [comment]
@rizchelwood, @amberleyromo 

> We should allow to customize rendered element via a prop, e.g. as="p" or as="strong"

 Maybe we should stay with 'block' tag: 
	- `p`
	- `div`
	- `span`
the `strong` tag as `b`, `i`, `em` should be used as children of `Text`

> VARIANT (bold, etc),

would be good to go through the app and do some of stocktaking to see what we need, and I would prefer not to using css values as a variant's name, so instead of `BOLD` maybe `EMPHESIZED`

> Let's allow for native margins instead of setting it in the code.

what about setting the values in the `theme` instead of relating to the native ones?

One more, what do you think about clearing `bottom-margin` if the component is `:last-child`

**Comment by rizchelwood** [comment]
Agreed on using 'block' tags and having tags like `strong`, etc be used as children. @Elanhant what do you think? 

On variant name, I'm open to other naming conventions (not css values), I think I was more trying to convey what that prop would be. 

Also, not tied to using native margins vs setting in `theme`. It would be good to see what we use in the code base now to see if we set this manually in most places. If so, it would be good to set in the `theme`

> One more, what do you think about clearing bottom-margin if the component is :last-child, this way there will not be conflicts with a container padding

I agree with this, I think we spoke about this before

**Comment by Elanhant** [comment]
Yeah I'm good with leaving format tags like `<strong>` out of our typography components; my suggestions was inspired by ["as" prop](https://emotion.sh/docs/styled#as-prop) from Emotion. 

Just to be sure though — are you ok with having `h1`-`h6` as possible tags?

**Comment by greglobinski** [comment]
>  are you ok with having h1-h6 as possible tags?

@Elanhant Don't we have a `core/Heading` for that?

**Comment by Elanhant** [comment]
Indeed, forgot about that 🙂

**Comment by Elanhant** [comment]
This is done in #106
