### ISSUE TITLE
Remove / reorganize components

### ISSUE THREAD

**Issue by greglobinski** [gatsby-inc/gatsby-interface#90]
##### Current list of `gatsby-interface` components:
- `Breadcrumb`
- `CopyButton`
- `FileUpload`
- `InputError`
- `Label`
- `Link`
- `Notification`
- `Radio`
- `SidebarNav`
- `StepsIndicator`
- `Tabs`
- `TextInput`
- `TextArea`
- `Toast`
- core: 
	- `AnchorButton`
	- `Announcement`
	- `Badge`
	- `Button`
	- `Heading`
	- `IntegrationRow`
	- `LinkButton`
	- `PricingCard`
	- `SettingsBlock`
	- `SettingsCard`
	- `Switch`
	- `Toggle`
	- `ToggleTip`
- skeletons:
	- `BaseAnchor`
	- `BaseButton`
	- `BaseHeading`
	- `BaseLink`
	- `ContentBox`

Actions:

1. Remove `core` folder, but should we also remove `skeletons` and go with complete flat structure for components?

2. Remove following components from the library and move it to `gatsbyjs.com/src/modules`:
- `SettingsBlock`
- `SettingsCard`
- `PricingCard`
- anything else?

3. Cherry pick following components from https://github.com/gatsby-inc/gatsby-interface/pull/52 and add them to the library, 
- `Avatar`
- `Carousel`
- the rest (`Testimonials`, `Person`, `DecoratedBlock`, `CtaBlock`) should stay in the cloud, but should be moved to the `modules` folder
	

cc/ @amberleyromo @rizchelwood @Elanhant @joshwcomeau @mfrachet

**Comment by joshwcomeau** [comment]
> Remove core folder, but should we also remove skeletons and go with complete flat structure for components?

I vote yes. The line feels kinda blurry to me (I'm not sure why `ContentBox` is a skeleton), and I think if we want to signify that some components are at the lowest level of abstraction and meant to be composed, the `Base` prefix solves for that.

> Remove following components from the library and move it to gatsbyjs.com/sroc/modules:

Sounds good to me :+1: I'm not familiar enough to know any others but yeah those 3 sound too specific for a component library.

> Cherry pick following components from #52 and add them to the library

Cool :+1:

**Comment by Elanhant** [comment]
Are there any updates on these? Perhaps we should split this into multiple issues linked to the [current milestone](https://github.com/gatsby-inc/gatsby-interface/milestone/1)?

**Comment by greglobinski** [comment]
Not much, I will create tomorrow a PR which removes `PricingCard`, because we no longer pull the component from the lib

**Comment by Elanhant** [comment]
> Not much, I will create tomorrow a PR which removes `PricingCard`, because we no longer pull the component from the lib

Cool, I will break this issue tomorrow  into several smaller ones so that it's easier to track and assign.

**Comment by mfrachet** [comment]
Is this still moving? 😊 I'm looking for integration row and setting blocks to be out of interface. I can make that modifications if necessary btw 😊

**Comment by Elanhant** [comment]
This seems to be done 🎉
